### ISSUE TITLE
Feature Request : Enforce consistency

### ISSUE THREAD

**Issue by coding-bunny** [rubocop-hq/minitest-style-guide#25]
## Is your feature request related to a problem? Please describe.

Something I've noticed in our repositories at work, is that we often end up with a mixture of the various checks inside a single test-suite : 

* `_()`
* `value()`
* `expect()`

Combined with the various checks like assert, must, refute, should.
I know several of them are being deprecated by minitest itself however.

## Describe the solution you'd like

I'm wondering whether we can write a Cop, that takes a specific configuration to say that all checks need to be done with one of the three lines above, and should be followed by the required syntax, being `must`, `should` or other plugin.

**Comment by coding-bunny** [comment]
Should I make a PR for the Style guide once we have a good name for the cop ?
Or just add the general idea?

**Comment by koic** [comment]
Here are some points I'm interested in adding to the rules in The Minitest Style guide.

- Consistent with one method (`_` or `value`, or `expect`) means fewer methods to represent instead. Is there a problem for Minitest users if they cannot select `_`,` value`, and `expect`?
- Which method is preferred for The Minitest Style Guide If one method is consistently OK?

**Comment by coding-bunny** [comment]
I don't think there's a problem with choosing/using any of the particular methods themselves. If I read the code correctly, the core method is `_` and the other two are just an alias for the method. Minitest however is encouraging/forcing people to use these methods instead of the global object methods that it originally implemented. (see the deprecation warnings), so in short, I don't think there's a problem with limiting/forcing a certain style, outside gaining the consistency in the code.

As for the second point...my personal preference would be to use `expect` to be inline with the RSpec DSL and most other testing frameworks from different languages.

**Comment by metaskills** [comment]
> Which method is preferred for The Minitest Style Guide

Agreed with @coding-bunny on the second point too, I would prefer `expect` since it aligns with other testing frameworks.

**Comment by duduribeiro** [comment]
I don't get this one 🤔 

the minitest way to check if values are equal is:

```
def test_if_equal
   assert_equal 2, something
end
```

**Comment by tejasbubane** [comment]
@duduribeiro This is the minitest spec syntax: http://docs.seattlerb.org/minitest/Minitest/Expectations.html

**Comment by tejasbubane** [comment]
> Which method is preferred for The Minitest Style Guide If one method is consistently OK?

@koic Since the [minitest docs](http://docs.seattlerb.org/minitest/Minitest/Expectations.html) are consistent with `_`, I think that is what we should suggest. Of course the cop will have configuration option to choose others.

**Comment by coding-bunny** [comment]
@tejasbubane agreed with that. Documentation examples as default and the rest configured. And then keep the code consistent.

Bonus if we can support auto correct.

**Comment by koic** [comment]
@tejasbubane Sounds good to me. I quoted from Minitest documentation.

```ruby
it "should still work in threads" do
  my_threaded_thingy do
    (1+1).must_equal 2                  # bad
    assert_equal 2, 1+1                 # good
    _(1 + 1).must_equal 2               # good
    value(1 + 1).must_equal 2           # good, also #expect
    _ { 1 + "1" }.must_raise TypeError  # good
  end
end
```

http://docs.seattlerb.org/minitest/Minitest/Expectations.html

I think that the style would be:

## The Minitest Style Guide

A part of this will be solved by https://github.com/rubocop-hq/rubocop-minitest/pull/63.

```ruby
# bad
(1+1).must_equal 2

# good
_(1 + 1).must_equal 2
value(1 + 1).must_equal 2
expect(1 + 1).must_equal 2
```

## Minitest Cop

This will be implemented as a different Minitest cop than https://github.com/rubocop-hq/rubocop-minitest/pull/63.

```ruby
# default
_(1 + 1).must_equal 2      # good
value(1 + 1).must_equal 2  # bad
expect(1 + 1).must_equal 2 # bad

# optional (value)
_(1 + 1).must_equal 2      # bad
value(1 + 1).must_equal 2  # good
expect(1 + 1).must_equal 2 # bad

# optional (expect)
_(1 + 1).must_equal 2      # bad
value(1 + 1).must_equal 2  # bad
expect(1 + 1).must_equal 2 # good
```

I'm not sure if implemetation of RuboCop Minitest should be enabled by default, anyway it could be included in the RuboCop Minitest.
